language: r
sudo: required
warnings_are_errors: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get jags
##  - sudo apt-get install r-cran-rjags

r_packages:
  - covr
  - R2jags
  - rjags  

after_success:
  - Rscript -e 'library(covr); codecov()'



